project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: true
  docx: default
# jats: default # binder
#  pdf: default
#  plos-pdf:
#    keep-tex: true
    
  

  # (other formats)
  # pdf: default

execute:
  freeze: auto



